# -*- coding: utf-8 -*-
"""ProjectCS-1314.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CtDcX-QYAddtpAyVm7k9ODcl0BLAaBYB

Dipesh Kala 2021 Second Summer Session- Intro Progarm/Prob Solving (CS-1314-010)
"""

import requests
import matplotlib.pyplot as plt


data2 = requests.get('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us/08-12-2021.csv').text
data = requests.get('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us/08-12-2020.csv').text
#got data from csv file on github for the date August 12 2020 and August 12 2021
data2 = data2.split('\n')
data = data.split('\n')

del data2 [0]
del data2 [-1]

del data [0]
del data [-1]
#delete the first row which just labels the states/provinces in order from 0 to 57
print("Data From August 12 2020\n")

totalcases = 0
totaldeaths = 0
leastcases = 100000000
leastdeaths = 1000000000
mostdeaths = 0
mostcases= 0
#set values to 0 so we can get a correct value from the data given
for state in data:
  rws = state.split(',')
  if int(rws[6]) <= leastdeaths: #by setting an if statement to change the least deaths to a new number everytime a number that is lower than the number before it so we can get the lowest amount in the list
    leastdeaths = int(rws[6]) 
  if int(rws[6]) > mostdeaths: #by setting an if statement to change the most deaths to a new number everytime a nuber that is bigger then the one before so we can get the biggest number in the list
    mostdeaths= int(rws[6])
  if int(rws[5]) <= leastcases: #same as the if statement above for leastdeaths except for cases of covid-19 instead
    leastcases = int(rws[5]) 
  if int(rws[5]) > mostcases: #same as the if statement above for the most deaths except for cases of covid-19 instead
    mostcases = int(rws[5])
  totalcases += int(rws[5])
  totaldeaths += int(rws[6])
  print(rws[0],rws[5],rws[6]) 
#The code above shows a list with all states and provinces in the csv file and also shows the confirmed cases of COVID-19 and deaths due to COVID-19 next to them
#also adds lines which will add the cases and deaths from each state/province and display them at the bottom of the list

print('\n')
print("The lowest amount of cases of COVID-19 as of August 12 2020 is:", leastcases)
print("The highest amount of cases of COVID-19 as of August 12 2020 is:", mostcases)
print("The lowest amount of deaths due to COVID-19 as of August 12 2020 is:", leastdeaths)
print("The highest amount of deaths due to COVID-19 as of August 12 2020 is:", mostdeaths)
print("The Total Number of cases of COVID-19 as of August 12 2020 is:",totalcases)
print("The Total Number of deaths due to COVID-19 as of August 12 2020 is:",totaldeaths)
print('\n')
print("Data From August 12 202\n")

totalcases2 = 0
totaldeaths2 = 0
leastcases2 = 100000000
leastdeaths2 = 1000000000
mostcases2= 0
mostdeaths2 = 0
for state in data2:
  rw = state.split(',')
  if int(rw[6]) <= leastdeaths2: #the if statements have the same functions as the statements above just for a new set of data
    leastdeaths2 = int(rw[6])
  if int(rw[6]) > mostdeaths2:
    mostdeaths2= int(rw[6])
  if int(rw[5]) <= leastcases2:
    leastcases2 = int(rw[5])
  if int(rw[5]) > mostcases2:
    mostcases2 = int(rw[5])
  totalcases2 += int(rw[5])
  totaldeaths2 += int(rw[6])
  print(rw[0],rw[5],rw[6]) 
#The code above shows a list with all states and provinces in the csv file and also shows the confirmed cases of COVID-19 and deaths due to COVID-19 next to them
#also adds lines which will add the cases and deaths from each state/province and display them at the bottom of the list

print('\n')
print("The lowest amount of cases of COVID-19 as of August 12 2021 is:", leastcases2)
print("The highest amount of cases of COVID-19 as of August 12 2021 is:", mostcases2)
print("The lowest amount of deaths due to COVID-19 as of August 12 2021 is:", leastdeaths2)
print("The highest amount of deaths due to COVID-19 as of August 12 2021 is:", mostdeaths2)
print("The Total Number of Cases of COVID-19 as of August 12 2021 is:",totalcases2)
print("The Total Number of Deaths Due to COVID-19 as of August 12 2021 is:",totaldeaths2)
print('\n')

plt.figure(figsize=[5,20])
for states in data2:
  row = states.split(',')
  xval2 = (row [0])
  yval2 = int(row [6])
  plt.barh(xval2, yval2)
  plt.title('COVID-19 Deaths on August 12 2021')
  plt.xlabel('Date')
  plt.ylabel('Deaths')
  plt.show
#Code to create a bar graph given the data from the csv file

print("From August 12 2020 to August 12 2021 there have been an increase of ",(totalcases2-totalcases),"confirmed COVID-19 cases." )
print("From August 12 2020 to August 12 2021 there have been an increase of ",(totaldeaths2-totaldeaths)," Deaths from COVID-19." )
print('\n')